version: '3.8'

services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver_db
    environment:
      SA_PASSWORD: "YourStrong@123"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    volumes:
      - sql_data:/var/opt/mssql

  web:
    image: dan3li0n/dan3li0n:latest
    container_name: my_web_app
    ports:
      - "8080:8080"
    depends_on:
      - sqlserver
    environment:
      SPRING_DATASOURCE_URL: "jdbc:sqlserver://sqlserver:1433;databaseName=TrinhHoanVu;encrypt=true;trustServerCertificate=true"
      SPRING_DATASOURCE_USERNAME: "sa"
      SPRING_DATASOURCE_PASSWORD: "YourStrong@123"

volumes:
  sql_data: